#!/usr/bin/env bash

# Shell script to run the Java application, checking for Java installation and version

if type -p java > /dev/null; then
    # Found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    # Found a java executable in JAVA_HOME 
    _java="$JAVA_HOME/bin/java"
else
    echo "Java is not installed or not found in PATH. Please install Java and ensure it is accessible." >&2
    exit 1
fi

if [[ "$_java" ]]; then
    version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | awk -F '.' '{sub("^$", "0", $2); print $1$2}')
    if [[ "$version" -ge "250" ]]; then
        java -jar target/qualitytool-1.0.jar $@
    else         
        echo Java version 25 or higher is required to run this application. Please update your Java installation.
    fi
fi


